services:
  # 1. DỊCH VỤ DATABASE (NHÀ KHO)
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    networks: # Thêm mạng
      - pg-network

  # 2. DỊCH VỤ ADMIN (VĂN PHÒNG)
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    volumes:
      - "./pgadmin_data:/var/lib/pgadmin"
    networks: # Thêm mạng
      - pg-network
    depends_on: # Bảo pgadmin chờ database
      - pgdatabase

  # 3. CÔNG VIỆC NẠP DỮ LIỆU (ROBOT)
  taxi-ingest:
    build: . # Tự build từ Dockerfile trong thư mục này
    networks:
      - pg-network
    depends_on: # QUAN TRỌNG: Chờ database sẵn sàng rồi mới chạy
      - pgdatabase

# KHỐI ĐỊNH NGHĨA MẠNG CHUNG
networks:
  pg-network:
    name: pg-network
    external: true